### ISSUE TITLE
Binary Search Tree: Handle insertion of duplicates differently

### ISSUE THREAD

**Issue by akuzminykh** [exercism/elixir#1042]
In the exercise "Binary Search Tree", the tests suggest to insert a duplicate value in the left subtree of the corresponding node. As far as I can tell, this is rather uncommon. It's more usual to have a list in a node that stores duplicates or to simply have a counter. I think, this should be expected in this exercise. Here is how I've solved the exercise:
```elixir
defmodule BinarySearchTree do
  @type bst_node :: %{data: any, count: integer, left: bst_node | nil, right: bst_node | nil}

  @doc """
  Create a new Binary Search Tree with root's value as the given 'data'
  """
  @spec new(any) :: bst_node
  def new(data) do
    %{data: data, count: 1, left: nil, right: nil}
  end

  @doc """
  Creates and inserts a node with its value as 'data' into the tree.
  """
  @spec insert(bst_node, any) :: bst_node
  def insert(tree, data)

  def insert(nil, data) do
    new(data)
  end

  def insert(tree, data) when tree.data == data do
    %{tree | count: tree.count + 1}
  end

  def insert(tree, data) when tree.data > data do
    %{tree | left: insert(tree.left, data)}
  end

  def insert(tree, data) when tree.data < data do
    %{tree | right: insert(tree.right, data)}
  end

  @doc """
  Traverses the Binary Search Tree in order and returns a list of each node's data.
  """
  @spec in_order(bst_node) :: [any]
  def in_order(tree)

  def in_order(nil) do
    []
  end

  def in_order(tree) do
    data =
      for _ <- 1..tree.count do
        tree.data
      end

    in_order(tree.left) ++ data ++ in_order(tree.right)
  end
end

```

**Comment by angelikatyborska** [comment]
@akuzminykh Thank you for the feedback!

Exercism uses a centralized repository called "problem specifications" with exercise definitions that all tracks implement. This implementation detail that a duplicate value goes to a left node and not in a duplication counter comes from that repository. [Here is the exact test definition](https://github.com/exercism/problem-specifications/blob/f6bc56834bf55bf2a23ca8f2084c84acaaa33569/exercises/binary-search-tree/canonical-data.json#L63-L79).

There is even an [open issue about adding the information about duplicates to the exercise description](https://github.com/exercism/problem-specifications/issues/1809).

My personal approach to maintaining the track is to follow the problem specifications as close as possible unless there are Elixir-specific reasons not to. I do that because the problem specifications are maintained by people that have way more knowledge and interest in computer science than I do and I trust them to make better decisions 🙂.

For those reasons, if you really believe that the current behavior with duplicate values is wrong, please open an issue in the [problem specifications repository](https://github.com/exercism/problem-specifications/). I personally have no opinions here and I will be happy to change the Elixir exercise after a change is made in problem specifications.
