### ISSUE TITLE
^^^/2: bitwise XOR no longer exists

### ISSUE THREAD

**Issue by kingdomcoding** [exercism/elixir#1142]
As of Elixir 1.12, `^^^/2: bitwise XOR` stopped existing.

Can the Secrets exercise be updated to match the latest Elixir 1.13?

**Comment by angelikatyborska** [comment]
@kingdomcoding Thank you for pointing this out! You can be assured that all of our exercises are tested in Elixir 1.13 and do work in 1.13. This means that `^^^` wasn't _really_ removed, otherwise we would get test failures in this repository and we would have noticed. In fact, there aren't even proper deprecation warnings about it. It just... got removed from the documentation, but still works. That is unusual.

We'll update the exercise soon!

**Comment by kingdomcoding** [comment]
Awesome

Thanks and well done
