### ISSUE TITLE
Darts test do not match the description

### ISSUE THREAD

**Issue by ahsf** [exercism/elixir#1204]
This would be a correct test I guess

```
defmodule DartsTest do
  use ExUnit.Case

  @tag :pending
  test "Missed target" do
    assert Darts.score({-11, 11}) == 0
  end

  @tag :pending
  test "On the outer circle" do
    assert Darts.score({0, 10}) == 1
  end

  @tag :pending
  test "On the middle circle" do
    assert Darts.score({-5, 0}) == 5
  end

  @tag :pending
  test "On the inner circle" do
    assert Darts.score({0, -1}) == 10
  end

  @tag :pending
  test "Exactly on centre" do
    assert Darts.score({0, 0}) == 10
  end

  @tag :pending
  test "Near the centre" do
    assert Darts.score({-0.1, -0.1}) == 10
  end

  @tag :pending
  test "Just within the inner circle" do
    assert Darts.score({0.7, 0.7}) == 10
  end

  @tag :pending
  test "Just outside the inner circle" do
    assert Darts.score({1.1, -1.1}) == 5
  end

  @tag :pending
  test "Just within the middle circle" do
    assert Darts.score({-5, 5}) == 5
  end

  @tag :pending
  test "Just outside the middle circle" do
    assert Darts.score({-5.1, -5.1}) == 1
  end

  @tag :pending
  test "Just within the outer circle" do
    assert Darts.score({-10, 10}) == 1
  end

  @tag :pending
  test "Just outside the outer circle" do
    assert Darts.score({10.1, -10.1}) == 0
  end

  @tag :pending
  test "Asymmetric position between the inner and middle circles" do
    assert Darts.score({0.5, -4}) == 5
  end
end
```

**Comment by angelikatyborska** [comment]
Can you please be more specific? Which tests exactly, which part of the description, and why? Also please check if those tests that you think contradict the description are defined in this file: https://github.com/exercism/problem-specifications/blob/main/exercises/darts/canonical-data.json If yes, you should create an issue in the [exercism/problem-specifications](https://github.com/exercism/problem-specifications) repository instead because that's where test definitions and descriptions come from for all the tracks on Exercism and we cannot change them in the Elixir track before they get changed there.

**Comment by ahsf** [comment]
OK, just to be sure, that I'm not just being stupid.
The description states: "The outer circle has a radius of 10 units"

https://github.com/exercism/problem-specifications/blob/main/exercises/darts/description.md

And in the spec I have this (9 is a miss)

```
{
  "uuid": "9033f731-0a3a-4d9c-b1c0-34a1c8362afb",
  "description": "Missed target",
  "property": "score",
  "input": {
    "x": -9,
    "y": 9
  },
  "expected": 0
},
```


https://github.com/exercism/problem-specifications/blob/main/exercises/darts/canonical-data.json

**Comment by jiegillet** [comment]
The spec is correct to call that a miss. 
You can draw it out to convince yourself. 
The coordinate (-9, 9) is approx 12.7 units from the center, you can calculate that the Pythagorean formula.
