### ISSUE TITLE
Beer Song tests fail. Tries to call lyrics/0, however only lyrics/1 is created by the exercise.

### ISSUE THREAD

**Issue by Pistrie** [exercism/elixir#1265]
Am I as a student supposed to create this function myself, or is this a faulty test? If I am supposed to create it myself it would be helpful if the exercise would clarify that in the description.

**Comment by glennj** [comment]
Read about default arguments at https://hexdocs.pm/elixir/Kernel.html#def/2

**Comment by angelikatyborska** [comment]
@Pistrie The way practice exercises on Exercism communicate to the student what is required is precisely by defining tests. So the existence of a test for `lyrics/0` with the description of "all verses" is how the exercise tells you to implement it. You will encounter this approach in many other exercises.

The tests are very unlikely to be accidentally wrong. All test definitions come from a global specifications repository that all languages use to implement them: https://github.com/exercism/problem-specifications, and this track has an example solution that is run against the test suite on every commit to this repository, so that all tests are guaranteed to compile and have a passing solution.

**Comment by Pistrie** [comment]
Alright, thanks for clearing that up 👍
