### ISSUE TITLE
Possibly an error with log-level

### ISSUE THREAD

**Issue by TheLugal** [exercism/elixir#1314]
I might be reading myself cross-eyed and be totally of the mark, but at the very least I feel there is a bit of ambiguity in the wording here.

> If the log label is _error_ or _fatal_, send the alert to the _ops_ team. If you receive a log with an _unknown_ label from a legacy system, send the alert to the _dev1_ team, other unknown labels should be sent to the _dev2_ team. All other log labels can be safely ignored.

I read this as *only* `:unknown` is sent to either dev1 or dev2.

However, the unit tests check for `assert LogLevel.alert_recipient(0, true) == :dev1`, and while it *is* a legacy system, `log code 0` is specified to be `:trace`, not `:unknown`, in the instructions.

https://github.com/exercism/elixir/blob/3194900f27d0ac07053c9b5ff30eb1a272d56e61/exercises/concept/log-level/test/log_level_test.exs#L69

Thanks for maintaining everything, I'm having a blast with the track so far :)

**Comment by angelikatyborska** [comment]
Hi! There is no error in the tests, but I agree there is something suboptimal in the instructions because this is not the first complaint I see about this task 🙂. I believe the confusion here is in the difference between a _code_ and a _label_ in the context of this exercise.

> However, the unit tests check for assert `LogLevel.alert_recipient(0, true) == :dev1`, and while it is a legacy system, `log code 0` is specified to be `:trace`, not `:unknown`, in the instructions.

Codes aren't mapped 1:1 to labels. The instructions of the previous step of the exercise state:

> Unknown log codes and codes unsupported in a legacy app should return an _unknown_ label.

So because in the first task, `assert LogLevel.to_label(0, true) == :unknown`, then in the second task, `assert LogLevel.alert_recipient(0, true) == :dev1`. The logic for deriving a label from a code and whether the system is a legacy system doesn't change between the two tasks of this exercise.

I hope the tiny changes from https://github.com/exercism/elixir/pull/1316 will help out with avoiding this misunderstanding.

Let me know if I have some huge blind spot and there are more confusing sentences there!
