### ISSUE TITLE
change_test.exs needs more test cases

### ISSUE THREAD

**Issue by MatthewMDavis** [exercism/elixir#239]
If a solution to the exercise for making change has to meet the following:

```
  test "generates change using only small coins when it is not possible to combine them with larger coins" do
    change = %{3 => 34, 100 => 0}
    assert Change.generate(102, [3, 100]) == {:ok, change}
  end

```

there need to be more complicated test cases. Right now, there's only only two values of coin, and there's only one of the larger value. Need test cases where simply breaking the largest coin once into change doesn't make it divisible by the smallest coin right away, and the process continues until it's finished. E.g.:

```
  @tag :pending
  test "generates change using ascending values of bigger coins" do
    change = %{3 => 9, 25 => 0, 100 => 1}
    assert Change.generate(127, [3, 25, 100]) == {:ok, change}
  end

  @tag :pending
  test "generates ascending change" do
    change = %{3 => 17, 25 => 0, 100 => 1}
    assert Change.generate(151, [3, 25, 100]) == {:ok, change}
  end
```

**Comment by parkerl** [comment]
Thanks @MatthewMDavis we'd love to see a PR on this.

**Comment by tejasbubane** [comment]
@devonestes You can add `pinned` label to make bot ignore this issue.

**Comment by angelikatyborska** [comment]
The exercise `change` in the Elixir track has changed significantly since September 2016. It has different input values, and it follows the problem specification (https://github.com/exercism/problem-specifications/blob/main/exercises/change/canonical-data.json). After #606 gets merged, it will be fully up to date to problem specifications, and it will have much better tests than it did in September 2016. I think that makes this issue obsolete. I'll close it for now, but if the author feels like this is not enough, I would recommend pitching in to https://github.com/exercism/problem-specifications instead.
