### ISSUE TITLE
Create mix file for each exercise

### ISSUE THREAD

**Issue by jhartwell** [exercism/elixir#382]
The erlang exercises use rebar3 in order to run their tests `rebar3 eunit`. It would be nice if we throw a mixfile into each exercise so we could just run mix test to test each file. I'm more than willing to help with this. I'm not sure if it should be broken into a single issue for each exercise or a giant issue that encompasses all exercises.

**Comment by NobbZ** [comment]
Even though I fully support you, it seems as if there was earlier discussion:

* #218 
* #245 

And to be honest, in case of erlang, the only reason I converted to rebar, was mainly because I was able to see longterm benefits which makes life for maintainers easier and it took me another year to actually implement those helpers partially, the official reason (rebar3 is the official buildtool of erlang) is only secondary ;)

**Comment by devonestes** [comment]
The reason I'm hesitant to go that route is because it seems like additional stuff to know for those in the very beginning of the track. There's an implied directory structure, and there's setup. Two files is just much simpler, and I think it's helpful to optimize for the extreme beginner, not only to Elixir but maybe even a newcomer to programming in general, since we want as few barriers to entry as possible.

That's generally been the decision amongst the maintainers (as evidenced previously), and I think it's still a good one, so we're going to stick with it.

Thanks for the input, though!

**Comment by shingtaklam1324** [comment]
@devonestes 

However it should be considered that some IDEs (Visual Studio Code for example) use the mix project for Intellisense, which in my opinion can be helpful for beginners to Elixir.
