### ISSUE TITLE
Add test in "Parallel Letter Frequency" to test for concurrency

### ISSUE THREAD

**Issue by percygrunwald** [exercism/elixir#446]
Currently you can pass all the tests in "Parallel Letter Frequency" without implementing any actual concurrency. I propose adding a test that checks that there is actually some concurrency by confirming that running `Frequency.frequency/2` with `workers > 1` actually results in increased performance.

I've created a proof of concept for this test:

```elixir
  test "actually implements concurrency" do
    huge_texts = List.duplicate(@ode_an_die_freude, 300)

    single_worker_fun = fn -> freq(huge_texts, 1) end
    parallel_workers_fun = fn -> freq(huge_texts, 4) end

    # warmup
    get_average_runtime(single_worker_fun)
    get_average_runtime(parallel_workers_fun)

    single_worker_runtime = get_average_runtime(single_worker_fun)
    parallel_workers_runtime = get_average_runtime(parallel_workers_fun)

    time_ratio = (parallel_workers_runtime / single_worker_runtime)

    assert time_ratio < 0.8
  end

  defp get_average_runtime(fun, iterations \\ 5) do
    1..iterations
    |> Enum.map(fn _index ->
      {runtime, _results} = :timer.tc(fun)
      runtime
    end)
    |> Enum.sum()
    |> Kernel./(iterations)
  end
```
Would love to hear feedback on my PoC if there's a better way to test for the improved performance. Obviously I have only tested this on my system, so I would be interested to see everyone else's results. On my system, running the test above with 4 workers halves the runtime of the function for `huge_texts` (time_ratio ~= 0.5), so I thought setting the limit to `0.8` would allow for some breathing room in implementation efficiency while also preventing any "false positives".

Thanks!

**Comment by NobbZ** [comment]
I do not like such a test, it might fail in environments that only have a single scheduler available.

If the counting happens in parallel should be evaluated by the mentor.

**Comment by Tuxified** [comment]
I understand the need for better tests, but I don't think it's feasible.

- parallel implementations might not always be faster (@NobbZ gave a good example)
- you'd have to specify the single worker implementation to test against (either given or extra assignment for mentee)

I also agree it's the mentors job to evaluate such a thing

**Comment by devonestes** [comment]
This would be too error prone to do, so we're not going to do it. Performance testing is notoriously difficult to get working consistently.

**Comment by devonestes** [comment]
@percygrunwald I don't think that looking at execution time is the best way to determine parallelism. It assumes there's a multi-core machine in there, which isn't always true. Also, a very inefficient parallel solution can be slower than a very efficient non-parallel solution.

Since parallelism is only accomplished on the BEAM by spawning processes, you _could_ write something that uses `erlang:trace/3` to check that at least one new process is spawned over the course of the function execution. This wouldn't guarantee parallelism, but if no other processes were spawned you can be sure that there _isn't_ any parallelism.

I wouldn't want to add that as a test, but we could possibly add some note somewhere if folks are interested. My concern with that is that it would possibly be _very_ confusing for newcomers since it's using an Erlang function call (nothing like it exists in Elixir), and because it gets pretty deep into OTP internals. The concept of a `spawn` and other OTP ideas might not even be really understood by someone using a `Task` for the firs time, for example.

So, if you want to explore that, you're more than welcome. It would take a fair amount of work to get this to a place where I'd be comfortable adding it somewhere to the exercise, but I can see it being something that a more advanced developer might appreciate, so I'm totally open to considering it.

**Comment by Tuxified** [comment]
Similar to how credo gives hints, we could do a similar thing by checking if folks used spawn, GenServer.start/start_link and one of the Task functions by walking the AST? I don't have much experience in that area, so not sure how reliable that might be.

**Comment by devonestes** [comment]
@Tuxified It would be way easier to use `:erlang.trace(:all, true, [:procs])` and then have something like:

```elixir
receive do
  {:trace, _, :spawn, pid, _} -> IO.puts("You spawned a process with the pid #{pid}!")
after
  1000 -> IO.puts("You didn't spawn a process!")
end
```

That would tell you if you've spawned a process or not without having to deal with static analysis.
