### ISSUE TITLE
Complete mentoring notes for core exercises

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/elixir#461]
Mentoring notes for elixir are found here: https://github.com/exercism/website-copy/tree/master/tracks/elixir/exercises

**Comment by angelikatyborska** [comment]
There will be no core exercises anymore in v3. All practice exercises will be equal, but some will get unlocked earlier than others based on their required concepts. Once v3 has been released, we will get a feel for which practice exercises are most popular in our track and we can focus on writing mentoring notes for those. My guess would that `leap` and `two-fer` become one of the most popular first exercises to solve.

Because of those structural changes to Exericsm, I think this issue should be closed as outdated.
