### ISSUE TITLE
rna-transcription: Is this a good core exercise?

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir#487]
As a sequelae to the discussions in #190 and #419 and in slack conversations,

Is this a good exercise for teaching the list concepts?  The majority of student solutions I mentor for this problem struggle with the concept of a charlist, but very rarely struggle with the concept of functional list manipulations.

My hypothesis is that this is because Elixir's Getting Started guide only touches very briefly on charlists in the context of strings so most of the students have no idea that the `?` operator even exists to return the codepoint.

So i have questions that I'm mulling over:
- Could the instructions be updated (eg. describe the `?` character)?
- Can the signature be updated (eg. use strings instead of charlists to represent the DNA)?
- Is there a better problem to teach these concepts to people?  

For the third question -- as I am going through the javascript track, resistor-color and resistor-color-duo seem to possibly touch on these concepts more clearly as there is less confusion around the charlist conversion.  Their example stops at two colors, but maybe we can reimagine it for `n`-color bands to promote the functional approach.

Thoughts?

**Comment by chriseyre2000** [comment]
I have been trying to improve the Elixir documentation to make the charlist and ?A notation easier to find. We can raise pull requests to add to the documentation.

**Comment by devonestes** [comment]
I sort of like having this here so we have at least one exercise that uses these data types. I think they’re important for learners to at least see once in the core track.

**Comment by neenjaw** [comment]
Ya, I think it is good for people to see and understand the data type too. 

I guess the issue I am trying to get is that when I see 80% of solutions I mentor have the same problem, there must be a gap somewhere and just want to explore ways to decrease that leap for students.

**Comment by chriseyre2000** [comment]
This is the first exercise on the track.

We could add a documentation link that explains ?A and 'A' == [?A] but that
might remove some early interactions with the student.

**Comment by nathanchere** [comment]
> This is the first exercise on the track. We could add a documentation link that explains ?A and 'A' == [?A] but that might remove some early interactions with the student.

Is interaction necessarily a goal? From a student perspective I've seen a lot of mentors where it doesn't matter what you submit, they will hold you up from progressing on a track despite a successful and even idiomatic solution for the sake of discussion. I would think that especially in the earlier challenges it would be better to give the students the tools they need for a challenge from the beginning rather than intentionally holding things back for the sake of artificially creating an opportunity for interaction.

(I realise different mentors will approach this differently and have their own idea of what constitutes adding value to the student experience)

**Comment by workingjubilee** [comment]
I agree with the desire to keep a charlist-dependent exercise, especially because they are likely to come up in Erlang <> Elixir interfaces, and Elixir programming will inevitably wind up interacting with underlying Erlang at some point. I agree with giving a hint, however, as it will point the student in the right direction. The core of the exercise is really the list-wrangling.

I would suggest changing the topic from "string" to "charlist", at the very minimum. It is a subtle but important hint, as yes, I did waste time looking at the String module based on that.

**Comment by neenjaw** [comment]
I also agree that there should be some exercise like this to teach these concepts.  I think the reason I opened the issue was that I find that a lot of students just don't even try to use a charlist which I think points to some sort of gap in: the problem spec, elixir basic documentation, or something.

One thing that has frustrated me in the other tracks is when the solution that the mentors want to see submitted isn't clearly defined, and then I have to resubmit another iteration because they didn't say they wanted to see _yadda-yadda_ feature in the solution in the first place.

I agree that the interaction is super important, but I don't want to frustrate people in telling them what they could have been able to figure out if they had more information **if** our problem spec is lacking.

**Comment by nathanchere** [comment]
"One thing that has frustrated me in the other tracks is when the solution that the mentors want to see submitted isn't clearly defined, and then I have to resubmit another iteration because they didn't say they wanted to see yadda-yadda feature in the solution in the first place"

1000x this. I have being mentoring on a few tracks and picked up a lot of tickets where another mentor has started with "you didn't do x" even though that's not indicated anywhere in the requirements and the student does have a valid solution. Worse still when it is sometimes not even what I would consider an ideal solution either. Then the student is will maybe attempt from scratch or need to unlearn the mental model they came up with in their own solution, and their new solution just sits in the queue. When I pick these up I'm more inclined to automatically pass these solutions as long as they did solve the tests properly and didn't do anything outright wrong. Then give the suggestion about what tools they could have used to approach the solution instead, point them to some other example solutions, and make a point of offering to mentor further if they want to try reactoring or rewriting this challenge again with the suggested changes.
