### ISSUE TITLE
Scale Generator exercise

### ISSUE THREAD

**Issue by DukeFruitarian** [exercism/elixir#490]
I've found 2 tests which don't work. Check it plz.

First: generate scale from tonic and pattern a Lydian scale (ScaleGeneratorTest) `assert ScaleGenerator.scale("a", @lydian_scale_pattern) == ~w"A B C# D# E F# G# A"` Why should it return common format instead of flat, if tonic is lowercase?

Second: `ScaleGenerator.find_chromatic_scale("F") == ~w"F Gb G Ab A Bb B C Db D Eb E F"` the opposite here. Why should it return flat variant, if tonic is capital?

Am i right about this? Are that bugs? If so, i'll happily make a pr

**Comment by neenjaw** [comment]
Hi Duke,

> I've found 2 tests which don't work. Check it plz.

When any commit builds on this repo, it is processed through TravisCI with an example solution which passes all of the tests.  THe solution must pass the tests in order for the commit to be approved.  Ergo, the tests do work.

I also have a solution that works, and I think it is very similar in construction to the example.  You can find it on my github repo if you wish.

> First: generate scale from tonic and pattern a Lydian scale (ScaleGeneratorTest) assert ScaleGenerator.scale("a", @lydian_scale_pattern) == ~w"A B C# D# E F# G# A" Why should it return common format instead of flat, if tonic is lowercase?

We were actually having  this discussion on slack about this, and from that, I googled it.  lowercase 'a' does not indicate the minor scale in the lydian mode scales, rather a indicates the ['A Lydian Mode'](https://www.basicmusictheory.com/a-lydian-mode) which has sharps, 'ab' (a-flat) should indicate the ['Ab Lydian Mode'](https://www.basicmusictheory.com/a-flat-lydian-mode) which has flats.

From what I could also discover through a search (albeit quick and I am not an expert) the capitalization of the key is more of a convention than a rule, so you find a lot of inconsistency.

> Second: ScaleGenerator.find_chromatic_scale("F") == ~w"F Gb G Ab A Bb B C Db D Eb E F" the opposite here. Why should it return flat variant, if tonic is capital?

Also from my search, I think this is more difficult to give a satisfying response because it relies on music theory and I am not an expert.  From what I gather, the reason the F chromatic scale commonly returns a flat scale because 'F' refers to 'F-major' which is a flat-based scale. Why? I don't know, but it is answer given in [section 3 on the F-chromatic-scale on basicmusictheory.com](https://www.basicmusictheory.com/f-chromatic-scale)

> Am i right about this? Are that bugs? If so, i'll happily make a pr

Even less satisfying, my answer is... I don't know.  This exercise is common all across exercism, so if it is a bug, it should likely be reviewed across the board. 

Overall -- to me -- the design of this exercise is elaborate and the test unit is detailed -- so it indicates to me that whomever designed the exercise must have known what they were doing and known more about this stuff than me.

So are they bugs? I don't know, but I think if you can find compelling reasoning it would be worth a PR.

Anyway, just my thoughts on it.

**Comment by DukeFruitarian** [comment]
Wow, thanks, you made a much more deep research, and i think it is ok as it is. I'll close the issue.
