### ISSUE TITLE
In response to automated-testing, should we specify a specific elixir version to support?

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir#514]
In response to exercism/automated-tests#29, there will (hopefully) soon be automated testing done against each submission.  The platform works with pre-built docker images so it seems there is some need to bake in a version of elixir to the image to run the tests. 

I know the track supports the major versions from 1.6-1.9, but is there a specific version that we want to use to run tests against and that we ask students to write against?

It seems in the thread that the tone is towards supporting a single version rather than a spectrum.

we can then also specify this version target to students in the `mix.exs` file version as well

Thoughts?

@devonestes @Cohen-Carlisle @rubysolo @parkerl (pinged as are listed as maintainers) @chriseyre2000 @NobbZ

**Comment by devonestes** [comment]
I would say it makes sense to target whatever is the most recent major version. It's probably fair to assume that learners are new-ish to the language, and they'd be installing the most recent version by default.

**Comment by NobbZ** [comment]
Du to slowlyness of major linux distributions this assumption is not safe.

And not everyone will be able to install through third party repositories or using `asdv-vm` or similar.

Still I think, latest minor release should be safe to use after. Erlang and Elixir rarely break compatibility. Only thing that might cause problems is compiling with `:warnings_as_errors` when student used an earlier version which had a function that has get deprecated in latest minor…

About the only thing in elixir what I think could cause real problems at the scope of the current exercises is how "imperative assignments" get treated since 1.7 or 1.8. Where we had a deprecation warning previously with "leaking scope", we now have no warning anymore and isolated scopes…

**Comment by filalex77** [comment]
Elixir needs a tool like rustup, just for a single purpose of installing and updating it.

I agree with @NobbZ on this one - many distros still package 1.8, and not moving that fast.

I'd say one minor release behind the current can strike a balance. So, 1.8 for now.

**Comment by NobbZ** [comment]
> I'd say one minor release behind the current can strike a balance. So, 1.8 for now.

To be honest, I think that will break more often, then assuming most recent would…

Assuming 1.9 is out and has new and shiny features not available in 1.8, it will break compilation when the student uses them (I think we can safely assume, most if not all will not update the `mix.exs` to reflect that), compilation will fail.

If they remember to update the version requirement, then the error will be meaningful at least and we can communicate the issue.

Though the other way round, compiling 1.8 code with 1.9, will cause some warnings in worst case.

We should communicate those warnings to the student, maybe in the analyser phase though…

So, even if the assumption "students use latest" will probably not hold, we still should be safely able to assume, that code targeting an old version will compile and run on latest anyway.

**Comment by neenjaw** [comment]
So to summarize a little

> 1. What version should we target publically?

Seems like it is between 1.8 and 1.9 (latest).  As @NobbZ pointed out as long as we don't compile with warnings as errors, it should still work. So we could run the track and the test runner at 1.9 and probably still be ok.

> 2. Will we impede people running lower than latest?

I think the only thing that may do that would be if we specified that in `mix.exs` (which at current, we have the version commented out). 

So people could run at whatever version and the real risk is just that the test runner may throw a warning.

This should be able to be accommodated in the current test runner spec.

**Comment by chriseyre2000** [comment]
I normally end up updating once a student uses a new feature.
Run the tests at 1.9 (which should now be stable) and see how it goes.

**Comment by neenjaw** [comment]
Okay, so test-runner will be built to 1.9.2 at this point (I'm using the new `System.get_env/2` in the ExUnit JSONFormatter, so that is a nice version for that), and let's see how it goes.

I think there will be a time soon where we will be specifying the target version on the exercism website (as per the other discussion thread on `exercism/automated-tests`), but the details of that are not set.

**Comment by Cohen-Carlisle** [comment]
Coming late to this conversation but I agree that using the latest version is best. Elixir is big on not breaking backwards compatibility so the real risk to ci is from students using a feature from a _newer_ version of elixir than ci is running.

We should leave the version loose in `mix.exs` to allow older versions if the student wishes since this should not be a problem for ci. It looks like 1.5 is still receiving security patches, so if we want to enforce some version, `"~> 1.5"` seems good to me.

**Comment by neenjaw** [comment]
Appreciate the input nonetheless!  Agreed on all points.
