### ISSUE TITLE
library-fees: Consider asking for a return date rather than datetime

### ISSUE THREAD

**Issue by SaschaMann** [exercism/elixir#802]
I doubt there's a library that checks the exact time, down to the second, for the return time rather than a return date.

This may not make sense for the exercise, I don't know how dates (but not datetimes) are handled in Elixir.

(I hope this kind of feedback is welcome, if not, please let me know)

**Comment by angelikatyborska** [comment]
From my perspective this kind of feedback is welcome, thanks 🙂

The exercise doesn't _check_ the exact time. It expect a datetime input, yes, but it only checks the date part.

I know nothing about libraries as a user... last time I used one was 8 years ago? But if I were designing a system for a library, I would definitely store checkout and return datetimes, not dates.

This would allow me to be precise about since when a book is available again, e.g. if I had an annoyed user come over that complained that they looked for a book, and it was not there, but then their friend looked for the same book on the same day and it was there. Or when trying to display this information on a website. I imagine this matters for books that are in demand.

So I guess we could change the exercise to calculate the expected return _date_, but I would like to keep the checkout and actual return as datetimes. E.g. change this part:

```elixir
  def return_datetime(checkout_datetime) do
    days = if before_noon?(checkout_datetime), do: 28, else: 29
    NaiveDateTime.add(checkout_datetime, days * 24 * 60 * 60, :second)
  end

  def days_late(planned_return_datetime, actual_return_datetime) do
    diff =
      Date.diff(
        NaiveDateTime.to_date(actual_return_datetime),
        NaiveDateTime.to_date(planned_return_datetime)
      )

    if diff < 0, do: 0, else: diff
  end
```

to this:

```elixir
  def return_date(checkout_datetime) do
    days = if before_noon?(checkout_datetime), do: 28, else: 29
    checkout_datetime
    |> NaiveDateTime.add(days * 24 * 60 * 60, :second)
    |> NaiveDateTime.to_date()
  end

  def days_late(planned_return_date, actual_return_datetime) do
    diff =
      Date.diff(
        NaiveDateTime.to_date(actual_return_datetime),
        planned_return_date
      )

    if diff < 0, do: 0, else: diff
  end
```

**Comment by SaschaMann** [comment]
> So I guess we could change the exercise to calculate the expected return date, but I would like to keep the checkout and actual return as datetimes.

Sounds good to me. The expected return date was what I had in mind, for the actual return date, a datetime makes sense.

Both as library staff and library user, you'd likely not work with exact minutes or seconds for the planned return time, which is why I think returning a date in `return_date` matches that better.

---

> This would allow me to be precise about since when a book is available again, e.g. if I had an annoyed user come over that complained that they looked for a book, and it was not there, but then their friend looked for the same book on the same day and it was there. Or when trying to display this information on a website. I imagine this matters for books that are in demand.

You'd likely need another datetime, since the time when a book is available again doesn't match the actual return time, because it has to be sorted back into the shelves etc. But that's unrelated to the suggestion above.

**Comment by angelikatyborska** [comment]
I'll work on this soon
