### ISSUE TITLE
Rational numbers: specs say input is float but is integer in tests

### ISSUE THREAD

**Issue by michallepicki** [exercism/elixir#868]
For the `pow_real` function, I wanted to use `Float.pow/2` but it failed in tests because the input is an integer (and that function guards against that), despite the included spec saying it will be float. I worked around this by using `:erlang.float/1` to cast an integer to float (one could also multiply by 1.0).

I didn't send a PR because I see this is one of the exercises ported to Elixir from [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/rational-numbers). In there the input indeed specifies integers, but description says this function (as name suggests) takes a real number.

Either the spec could be updated to say `number` (which is `integer | float`), and possibly there could be a hint in description about handling both, or maybe Elixir test cases should use floats as input?

**Comment by angelikatyborska** [comment]
@michallepicki the implementation (tests) are correct, the typespec is wrong. To match the tests, it should say:
```elixir
@spec pow_real(x :: integer, n :: rational) :: float
```

Not even `| float` becayse according to the problem specifications there are no float inputs in any tests. I'm a lazy maintainer and try to follow problem specifications to the letter unless really necessary so that I don't have to think too much. A lot of other people thought through those problems way more than I have 😁 

Would you want to do a tiny PR?

**Comment by michallepicki** [comment]
Sure, will do!
