### ISSUE TITLE
The tests for `NucleotideCount` does not include the error scenario

### ISSUE THREAD

**Issue by fmv1992** [exercism/elixir#886]
The tests for `NucleotideCount` does not include the error scenario

[The tests for `NucleotideCount`](https://github.com/exercism/elixir/blob/d5f3834445cacf93ec7bfa9048013c21dce4c65a/exercises/practice/nucleotide-count/test/nucleotide_count_test.exs#L1) do not cover:

> If the string contains characters that aren't A, C, G, or T then it is invalid and you should signal an error.

I'm not sure if this is intentional or not.

**Comment by angelikatyborska** [comment]
@fmv1992 Thanks for the issue! This is by design. We even documented that in this file: https://github.com/exercism/elixir/blob/main/exercises/practice/nucleotide-count/.meta/design.md

Long story short, it had to do with making some of the exercises very easy so that they have fewer prerequisite concepts and get unlocked faster.
