### ISSUE TITLE
"Secrets" exercise -- task 2 is written backwards

### ISSUE THREAD

**Issue by Eiermann** [exercism/elixir#887]
Task 2 in the Secrets exercise states:

```
Implement Secrets.secret_subtract/1. It should return a function which takes one
argument and subtracts from it the secret passed in to secret_subtract.

subtractor = Secrets.secret_subtract(2)
subtractor.(3)
# => 1
```

So according to the description above, the returned function should take one argument (in the example, this argument is 3) and subtract is from the secret passed in to ```secret_subtract``` (in this case, the passed in secret is 2). Subtracting 3 from 2 is: ```2-3``` which is ```-1```, but the example says ```1``` is the answer and the tests follow the same pattern of subtracting the secret number from the number passed in to the function.

I'm happy to submit a PR against this (though if someone else can knock this out quickly my feelings won't be hurt), I just need to know if the description should be changed to match the tests or the tests (and example) changed to match the description.

**Comment by angelikatyborska** [comment]
I am pretty sure the description is correct. Let me analyze it with an example.

This is a correct implementation:
```
  def secret_subtract(secret) do
    fn x -> x - secret end
  end
```

The description says:

> It should return a function which takes one argument

The returned function takes one argument, `x`.

> and subtracts from it

Subtracts **from** the argument, the argument is `x`, so **from** x is `x - ...`

I wouldn't want to change this description because I wrote all of them to follow the same pattern:
- "and adds to it the secret"
- "and subtracts from it the secret"
- "and multiplies it by the secret"
- "and divides it by the secret"

**Comment by Eiermann** [comment]
You're right, I read too quickly and got "subtracts it from" rather than "subtracts from it."
