### ISSUE TITLE
Order of concept exercises

### ISSUE THREAD

**Issue by petemcfarlane** [exercism/elixir#927]
Hey, may I suggest swapping the order of the **RPN Calculator** with the **Stack Underflow** exercise? The RPN concepts are _Errors_ and _Try/Rescue_, whilst the Stack Underflow is about _Exceptions_. I struggled to understand what the `RuntimeError` was a struct - I even asked for personal mentoring on this (which was great!) but then the next exercise explained that all errors implement the Exception behaviour, and that helped crystallise my understanding. I think if the exercises were the other way around I probably wouldn't have needed the extra help from a mentor, and it might help others on their learning journey too? I assume it's as simple as changing a config file, but I'm not too familiar with the Exercism v3 structure.
Thanks, and great job!

**Comment by angelikatyborska** [comment]
We should probably add more explanations to the introduction of `RPN Calculator` about what those errors that you rescue are. I'll try to open a PR. (cc @neenjaw)

I am not convinced swapping order is a good idea mainly because defining your own exceptions is something that usually only library authors have to do (I haven't seen it done in any of my apps), while ever user of Elixir sooner or later will hit an exception and might wonder how to rescue it.
